name: Daily Vitoria Scraper (Quarterly)

on:
  schedule:
    - cron: '5,15,25,35,45,55 * * * *' # Cada 10 minutos (a las :05, :15, :25, :35, :45, :55)
  workflow_dispatch: # Permite ejecución manual

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper and Rewriter
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_REWRITE_KEY: ${{ secrets.GROQ_REWRITE_KEY }}
          GROQ_REWRITE_2: ${{ secrets.GROQ_REWRITE_2 }}
          GROQ_REWRITE_3: ${{ secrets.GROQ_REWRITE_3 }}
          GROQ_POLISH_KEY: ${{ secrets.GROQ_POLISH_KEY }}
          GROQ_POLISH2: ${{ secrets.GROQ_POLISH2 }}
          GROQ_EUSKERA2: ${{ secrets.GROQ_EUSKERA2 }}
          GROQ_TRANSLATION_KEY: ${{ secrets.GROQ_TRANSLATION_KEY }}
          groq_KEY: ${{ secrets.groq_KEY }}
          GROQ_RESUMEN: ${{ secrets.GROQ_RESUMEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scraper/multi_scraper.py
          python scraper/parallel_rewrite.py
          python scraper/update_mood.py
          python scraper/generate_summary.py
          python scraper/update_podcast.py
          python scraper/enviar_telegram.py

      - name: Check and fix missing images
        run: |
          python scraper/fix_missing_images_ddg.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Vitoria Scraper Bot"
          git config --global user.email "bot@vitoriachronicle.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git add data/news.json scraper/history.json data/mood_history.json data/podcast.json data/sent_news_ids.json data/resumen.png
          git diff --cached --quiet || git commit -m "Automated news update - $(date +'%Y-%m-%d %H:%M')"
          git pull --rebase --autostash origin main
          git push origin main